// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Awesome.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__AWESOME_HPP
#define FAST_DDS_GENERATED__AWESOME_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(AWESOME_SOURCE)
#define AWESOME_DllAPI __declspec( dllexport )
#else
#define AWESOME_DllAPI __declspec( dllimport )
#endif // AWESOME_SOURCE
#else
#define AWESOME_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define AWESOME_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure Awesome defined by the user in the IDL file.
 * @ingroup Awesome
 */
class Awesome
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport Awesome()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~Awesome()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object Awesome that will be copied.
     */
    eProsima_user_DllExport Awesome(
            const Awesome& x)
    {
                    m_ButAmI = x.m_ButAmI;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object Awesome that will be copied.
     */
    eProsima_user_DllExport Awesome(
            Awesome&& x) noexcept
    {
        m_ButAmI = x.m_ButAmI;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object Awesome that will be copied.
     */
    eProsima_user_DllExport Awesome& operator =(
            const Awesome& x)
    {

                    m_ButAmI = x.m_ButAmI;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object Awesome that will be copied.
     */
    eProsima_user_DllExport Awesome& operator =(
            Awesome&& x) noexcept
    {

        m_ButAmI = x.m_ButAmI;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x Awesome object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const Awesome& x) const
    {
        return (m_ButAmI == x.m_ButAmI);
    }

    /*!
     * @brief Comparison operator.
     * @param x Awesome object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const Awesome& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member ButAmI
     * @param _ButAmI New value for member ButAmI
     */
    eProsima_user_DllExport void ButAmI(
            bool _ButAmI)
    {
        m_ButAmI = _ButAmI;
    }

    /*!
     * @brief This function returns the value of member ButAmI
     * @return Value of member ButAmI
     */
    eProsima_user_DllExport bool ButAmI() const
    {
        return m_ButAmI;
    }

    /*!
     * @brief This function returns a reference to member ButAmI
     * @return Reference to member ButAmI
     */
    eProsima_user_DllExport bool& ButAmI()
    {
        return m_ButAmI;
    }



private:

    bool m_ButAmI{false};

};

#endif // _FAST_DDS_GENERATED_AWESOME_HPP_


