// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MoveCommand.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__EIVA_GAME_MOVECOMMAND_HPP
#define FAST_DDS_GENERATED__EIVA_GAME_MOVECOMMAND_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MOVECOMMAND_SOURCE)
#define MOVECOMMAND_DllAPI __declspec( dllexport )
#else
#define MOVECOMMAND_DllAPI __declspec( dllimport )
#endif // MOVECOMMAND_SOURCE
#else
#define MOVECOMMAND_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MOVECOMMAND_DllAPI
#endif // _WIN32

namespace EIVA {

namespace Game {

/*!
 * @brief This class represents the structure MoveCommand defined by the user in the IDL file.
 * @ingroup MoveCommand
 */
class MoveCommand
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MoveCommand()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MoveCommand()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MoveCommand that will be copied.
     */
    eProsima_user_DllExport MoveCommand(
            const MoveCommand& x)
    {
                    m_player_id = x.m_player_id;

                    m_dir_x = x.m_dir_x;

                    m_dir_y = x.m_dir_y;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object MoveCommand that will be copied.
     */
    eProsima_user_DllExport MoveCommand(
            MoveCommand&& x) noexcept
    {
        m_player_id = x.m_player_id;
        m_dir_x = x.m_dir_x;
        m_dir_y = x.m_dir_y;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MoveCommand that will be copied.
     */
    eProsima_user_DllExport MoveCommand& operator =(
            const MoveCommand& x)
    {

                    m_player_id = x.m_player_id;

                    m_dir_x = x.m_dir_x;

                    m_dir_y = x.m_dir_y;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object MoveCommand that will be copied.
     */
    eProsima_user_DllExport MoveCommand& operator =(
            MoveCommand&& x) noexcept
    {

        m_player_id = x.m_player_id;
        m_dir_x = x.m_dir_x;
        m_dir_y = x.m_dir_y;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x MoveCommand object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const MoveCommand& x) const
    {
        return (m_player_id == x.m_player_id &&
           m_dir_x == x.m_dir_x &&
           m_dir_y == x.m_dir_y);
    }

    /*!
     * @brief Comparison operator.
     * @param x MoveCommand object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const MoveCommand& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member player_id
     * @param _player_id New value for member player_id
     */
    eProsima_user_DllExport void player_id(
            int32_t _player_id)
    {
        m_player_id = _player_id;
    }

    /*!
     * @brief This function returns the value of member player_id
     * @return Value of member player_id
     */
    eProsima_user_DllExport int32_t player_id() const
    {
        return m_player_id;
    }

    /*!
     * @brief This function returns a reference to member player_id
     * @return Reference to member player_id
     */
    eProsima_user_DllExport int32_t& player_id()
    {
        return m_player_id;
    }


    /*!
     * @brief This function sets a value in member dir_x
     * @param _dir_x New value for member dir_x
     */
    eProsima_user_DllExport void dir_x(
            float _dir_x)
    {
        m_dir_x = _dir_x;
    }

    /*!
     * @brief This function returns the value of member dir_x
     * @return Value of member dir_x
     */
    eProsima_user_DllExport float dir_x() const
    {
        return m_dir_x;
    }

    /*!
     * @brief This function returns a reference to member dir_x
     * @return Reference to member dir_x
     */
    eProsima_user_DllExport float& dir_x()
    {
        return m_dir_x;
    }


    /*!
     * @brief This function sets a value in member dir_y
     * @param _dir_y New value for member dir_y
     */
    eProsima_user_DllExport void dir_y(
            float _dir_y)
    {
        m_dir_y = _dir_y;
    }

    /*!
     * @brief This function returns the value of member dir_y
     * @return Value of member dir_y
     */
    eProsima_user_DllExport float dir_y() const
    {
        return m_dir_y;
    }

    /*!
     * @brief This function returns a reference to member dir_y
     * @return Reference to member dir_y
     */
    eProsima_user_DllExport float& dir_y()
    {
        return m_dir_y;
    }



private:

    int32_t m_player_id{0};
    float m_dir_x{0.0};
    float m_dir_y{0.0};

};

} // namespace Game

} // namespace EIVA

#endif // _FAST_DDS_GENERATED_EIVA_GAME_MOVECOMMAND_HPP_


