// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MoveCommandTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "MoveCommandTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "MoveCommand.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace EIVA {
namespace Game {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_MoveCommand_type_identifier(
        TypeIdentifierPair& type_ids_MoveCommand)
{

    ReturnCode_t return_code_MoveCommand {eprosima::fastdds::dds::RETCODE_OK};
    return_code_MoveCommand =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EIVA::Game::MoveCommand", type_ids_MoveCommand);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_MoveCommand)
    {
        StructTypeFlag struct_flags_MoveCommand = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_MoveCommand = "EIVA::Game::MoveCommand";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_MoveCommand;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_MoveCommand;
        CompleteTypeDetail detail_MoveCommand = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_MoveCommand, ann_custom_MoveCommand, type_name_MoveCommand.to_string());
        CompleteStructHeader header_MoveCommand;
        header_MoveCommand = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_MoveCommand);
        CompleteStructMemberSeq member_seq_MoveCommand;
        {
            TypeIdentifierPair type_ids_player_id;
            ReturnCode_t return_code_player_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_player_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_player_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_player_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "player_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_player_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_player_id = 0x00000000;
            bool common_player_id_ec {false};
            CommonStructMember common_player_id {TypeObjectUtils::build_common_struct_member(member_id_player_id, member_flags_player_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_player_id, common_player_id_ec))};
            if (!common_player_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure player_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_player_id = "player_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_player_id;
            ann_custom_MoveCommand.reset();
            CompleteMemberDetail detail_player_id = TypeObjectUtils::build_complete_member_detail(name_player_id, member_ann_builtin_player_id, ann_custom_MoveCommand);
            CompleteStructMember member_player_id = TypeObjectUtils::build_complete_struct_member(common_player_id, detail_player_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_MoveCommand, member_player_id);
        }
        {
            TypeIdentifierPair type_ids_dir_x;
            ReturnCode_t return_code_dir_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_dir_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_dir_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_dir_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "dir_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_dir_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_dir_x = 0x00000001;
            bool common_dir_x_ec {false};
            CommonStructMember common_dir_x {TypeObjectUtils::build_common_struct_member(member_id_dir_x, member_flags_dir_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_dir_x, common_dir_x_ec))};
            if (!common_dir_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure dir_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_dir_x = "dir_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_dir_x;
            ann_custom_MoveCommand.reset();
            CompleteMemberDetail detail_dir_x = TypeObjectUtils::build_complete_member_detail(name_dir_x, member_ann_builtin_dir_x, ann_custom_MoveCommand);
            CompleteStructMember member_dir_x = TypeObjectUtils::build_complete_struct_member(common_dir_x, detail_dir_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_MoveCommand, member_dir_x);
        }
        {
            TypeIdentifierPair type_ids_dir_y;
            ReturnCode_t return_code_dir_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_dir_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_dir_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_dir_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "dir_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_dir_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_dir_y = 0x00000002;
            bool common_dir_y_ec {false};
            CommonStructMember common_dir_y {TypeObjectUtils::build_common_struct_member(member_id_dir_y, member_flags_dir_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_dir_y, common_dir_y_ec))};
            if (!common_dir_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure dir_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_dir_y = "dir_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_dir_y;
            ann_custom_MoveCommand.reset();
            CompleteMemberDetail detail_dir_y = TypeObjectUtils::build_complete_member_detail(name_dir_y, member_ann_builtin_dir_y, ann_custom_MoveCommand);
            CompleteStructMember member_dir_y = TypeObjectUtils::build_complete_struct_member(common_dir_y, detail_dir_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_MoveCommand, member_dir_y);
        }
        CompleteStructType struct_type_MoveCommand = TypeObjectUtils::build_complete_struct_type(struct_flags_MoveCommand, header_MoveCommand, member_seq_MoveCommand);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_MoveCommand, type_name_MoveCommand.to_string(), type_ids_MoveCommand))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "EIVA::Game::MoveCommand already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace Game

} // namespace EIVA

