// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file WeaponCommand.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__EIVA_GAME_WEAPONCOMMAND_HPP
#define FAST_DDS_GENERATED__EIVA_GAME_WEAPONCOMMAND_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(WEAPONCOMMAND_SOURCE)
#define WEAPONCOMMAND_DllAPI __declspec( dllexport )
#else
#define WEAPONCOMMAND_DllAPI __declspec( dllimport )
#endif // WEAPONCOMMAND_SOURCE
#else
#define WEAPONCOMMAND_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define WEAPONCOMMAND_DllAPI
#endif // _WIN32

namespace EIVA {

namespace Game {

/*!
 * @brief This class represents the enumeration WeaponType defined by the user in the IDL file.
 * @ingroup WeaponCommand
 */
enum class WeaponType : int32_t
{
    Gun,
    Shield,
    SlowFiled
};
/*!
 * @brief This class represents the structure WeaponCommand defined by the user in the IDL file.
 * @ingroup WeaponCommand
 */
class WeaponCommand
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport WeaponCommand()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~WeaponCommand()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object WeaponCommand that will be copied.
     */
    eProsima_user_DllExport WeaponCommand(
            const WeaponCommand& x)
    {
                    m_player_id = x.m_player_id;

                    m_weapon = x.m_weapon;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object WeaponCommand that will be copied.
     */
    eProsima_user_DllExport WeaponCommand(
            WeaponCommand&& x) noexcept
    {
        m_player_id = x.m_player_id;
        m_weapon = x.m_weapon;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object WeaponCommand that will be copied.
     */
    eProsima_user_DllExport WeaponCommand& operator =(
            const WeaponCommand& x)
    {

                    m_player_id = x.m_player_id;

                    m_weapon = x.m_weapon;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object WeaponCommand that will be copied.
     */
    eProsima_user_DllExport WeaponCommand& operator =(
            WeaponCommand&& x) noexcept
    {

        m_player_id = x.m_player_id;
        m_weapon = x.m_weapon;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x WeaponCommand object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const WeaponCommand& x) const
    {
        return (m_player_id == x.m_player_id &&
           m_weapon == x.m_weapon);
    }

    /*!
     * @brief Comparison operator.
     * @param x WeaponCommand object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const WeaponCommand& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member player_id
     * @param _player_id New value for member player_id
     */
    eProsima_user_DllExport void player_id(
            int32_t _player_id)
    {
        m_player_id = _player_id;
    }

    /*!
     * @brief This function returns the value of member player_id
     * @return Value of member player_id
     */
    eProsima_user_DllExport int32_t player_id() const
    {
        return m_player_id;
    }

    /*!
     * @brief This function returns a reference to member player_id
     * @return Reference to member player_id
     */
    eProsima_user_DllExport int32_t& player_id()
    {
        return m_player_id;
    }


    /*!
     * @brief This function sets a value in member weapon
     * @param _weapon New value for member weapon
     */
    eProsima_user_DllExport void weapon(
            WeaponType _weapon)
    {
        m_weapon = _weapon;
    }

    /*!
     * @brief This function returns the value of member weapon
     * @return Value of member weapon
     */
    eProsima_user_DllExport WeaponType weapon() const
    {
        return m_weapon;
    }

    /*!
     * @brief This function returns a reference to member weapon
     * @return Reference to member weapon
     */
    eProsima_user_DllExport WeaponType& weapon()
    {
        return m_weapon;
    }



private:

    int32_t m_player_id{0};
    WeaponType m_weapon{WeaponType::Gun};

};

} // namespace Game

} // namespace EIVA

#endif // _FAST_DDS_GENERATED_EIVA_GAME_WEAPONCOMMAND_HPP_


