// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file WeaponCommandTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "WeaponCommandTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "WeaponCommand.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace EIVA {
namespace Game {
void register_WeaponType_type_identifier(
        TypeIdentifierPair& type_ids_WeaponType)
{
    ReturnCode_t return_code_WeaponType {eprosima::fastdds::dds::RETCODE_OK};
    return_code_WeaponType =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EIVA::Game::WeaponType", type_ids_WeaponType);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_WeaponType)
    {
        EnumTypeFlag enum_flags_WeaponType = 0;
        BitBound bit_bound_WeaponType = 32;
        CommonEnumeratedHeader common_WeaponType = TypeObjectUtils::build_common_enumerated_header(bit_bound_WeaponType);
        QualifiedTypeName type_name_WeaponType = "EIVA::Game::WeaponType";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_WeaponType;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_WeaponType;
        CompleteTypeDetail detail_WeaponType = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_WeaponType, ann_custom_WeaponType, type_name_WeaponType.to_string());
        CompleteEnumeratedHeader header_WeaponType = TypeObjectUtils::build_complete_enumerated_header(common_WeaponType, detail_WeaponType);
        CompleteEnumeratedLiteralSeq literal_seq_WeaponType;
        {
            EnumeratedLiteralFlag flags_Gun = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_Gun = TypeObjectUtils::build_common_enumerated_literal(0, flags_Gun);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Gun;
            ann_custom_WeaponType.reset();
            MemberName name_Gun = "Gun";
            CompleteMemberDetail detail_Gun = TypeObjectUtils::build_complete_member_detail(name_Gun, member_ann_builtin_Gun, ann_custom_WeaponType);
            CompleteEnumeratedLiteral literal_Gun = TypeObjectUtils::build_complete_enumerated_literal(common_Gun, detail_Gun);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_WeaponType, literal_Gun);
        }
        {
            EnumeratedLiteralFlag flags_Shield = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_Shield = TypeObjectUtils::build_common_enumerated_literal(1, flags_Shield);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_Shield;
            ann_custom_WeaponType.reset();
            MemberName name_Shield = "Shield";
            CompleteMemberDetail detail_Shield = TypeObjectUtils::build_complete_member_detail(name_Shield, member_ann_builtin_Shield, ann_custom_WeaponType);
            CompleteEnumeratedLiteral literal_Shield = TypeObjectUtils::build_complete_enumerated_literal(common_Shield, detail_Shield);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_WeaponType, literal_Shield);
        }
        {
            EnumeratedLiteralFlag flags_SlowField = TypeObjectUtils::build_enumerated_literal_flag(false);
            CommonEnumeratedLiteral common_SlowField = TypeObjectUtils::build_common_enumerated_literal(2, flags_SlowField);
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_SlowField;
            ann_custom_WeaponType.reset();
            MemberName name_SlowField = "SlowField";
            CompleteMemberDetail detail_SlowField = TypeObjectUtils::build_complete_member_detail(name_SlowField, member_ann_builtin_SlowField, ann_custom_WeaponType);
            CompleteEnumeratedLiteral literal_SlowField = TypeObjectUtils::build_complete_enumerated_literal(common_SlowField, detail_SlowField);
            TypeObjectUtils::add_complete_enumerated_literal(literal_seq_WeaponType, literal_SlowField);
        }
        CompleteEnumeratedType enumerated_type_WeaponType = TypeObjectUtils::build_complete_enumerated_type(enum_flags_WeaponType, header_WeaponType,
                literal_seq_WeaponType);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_enumerated_type_object(enumerated_type_WeaponType, type_name_WeaponType.to_string(), type_ids_WeaponType))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                "EIVA::Game::WeaponType already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_WeaponCommand_type_identifier(
        TypeIdentifierPair& type_ids_WeaponCommand)
{

    ReturnCode_t return_code_WeaponCommand {eprosima::fastdds::dds::RETCODE_OK};
    return_code_WeaponCommand =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EIVA::Game::WeaponCommand", type_ids_WeaponCommand);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_WeaponCommand)
    {
        StructTypeFlag struct_flags_WeaponCommand = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_WeaponCommand = "EIVA::Game::WeaponCommand";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_WeaponCommand;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_WeaponCommand;
        CompleteTypeDetail detail_WeaponCommand = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_WeaponCommand, ann_custom_WeaponCommand, type_name_WeaponCommand.to_string());
        CompleteStructHeader header_WeaponCommand;
        header_WeaponCommand = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_WeaponCommand);
        CompleteStructMemberSeq member_seq_WeaponCommand;
        {
            TypeIdentifierPair type_ids_player_id;
            ReturnCode_t return_code_player_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_player_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_int32_t", type_ids_player_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_player_id)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "player_id Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_player_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_player_id = 0x00000000;
            bool common_player_id_ec {false};
            CommonStructMember common_player_id {TypeObjectUtils::build_common_struct_member(member_id_player_id, member_flags_player_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_player_id, common_player_id_ec))};
            if (!common_player_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure player_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_player_id = "player_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_player_id;
            ann_custom_WeaponCommand.reset();
            CompleteMemberDetail detail_player_id = TypeObjectUtils::build_complete_member_detail(name_player_id, member_ann_builtin_player_id, ann_custom_WeaponCommand);
            CompleteStructMember member_player_id = TypeObjectUtils::build_complete_struct_member(common_player_id, detail_player_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_WeaponCommand, member_player_id);
        }
        {
            TypeIdentifierPair type_ids_weapon;
            ReturnCode_t return_code_weapon {eprosima::fastdds::dds::RETCODE_OK};
            return_code_weapon =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "EIVA::Game::WeaponType", type_ids_weapon);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_weapon)
            {
                ::EIVA::Game::register_WeaponType_type_identifier(type_ids_weapon);
            }
            StructMemberFlag member_flags_weapon = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_weapon = 0x00000001;
            bool common_weapon_ec {false};
            CommonStructMember common_weapon {TypeObjectUtils::build_common_struct_member(member_id_weapon, member_flags_weapon, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_weapon, common_weapon_ec))};
            if (!common_weapon_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure weapon member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_weapon = "weapon";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_weapon;
            ann_custom_WeaponCommand.reset();
            CompleteMemberDetail detail_weapon = TypeObjectUtils::build_complete_member_detail(name_weapon, member_ann_builtin_weapon, ann_custom_WeaponCommand);
            CompleteStructMember member_weapon = TypeObjectUtils::build_complete_struct_member(common_weapon, detail_weapon);
            TypeObjectUtils::add_complete_struct_member(member_seq_WeaponCommand, member_weapon);
        }
        CompleteStructType struct_type_WeaponCommand = TypeObjectUtils::build_complete_struct_type(struct_flags_WeaponCommand, header_WeaponCommand, member_seq_WeaponCommand);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_WeaponCommand, type_name_WeaponCommand.to_string(), type_ids_WeaponCommand))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "EIVA::Game::WeaponCommand already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace Game

} // namespace EIVA

